### ISSUE TITLE
[Bug]: Cant run mongoBot.pyw

### ISSUE THREAD

**Issue by rawnullbyte** [Pilot1782/bad_copeheimer#171]
### What happened?

A bug happened! When I run the mongoBot.pyw it says error like: TypeError: 'Logger' object is not callable

### Operating Sys

Windows

### Branch

- [X] Tried `dev-builds`

### Relevant log output

```shell
C:\Users\Laptop\AppData\Local\Programs\Python\Python312\Lib\site-packages\cryptography\x509\base.py:594: CryptographyDeprecationWarning: Parsed a negative serial number, which is disallowed by RFC 5280.
  return rust_x509.load_der_x509_certificate(data)
Traceback (most recent call last):
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python312\Lib\site-packages\interactions\client\client.py", line 963, in astart
    await self._connection_state.start()
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python312\Lib\site-packages\interactions\api\gateway\state.py", line 76, in start
    self.wrapped_logger(logging.INFO, "Starting Shard")
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python312\Lib\site-packages\interactions\api\gateway\state.py", line 142, in wrapped_logger
    self.logger.log(level, f"Shard ID {self.shard_id} | {message}", **kwargs)
TypeError: 'Logger' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Laptop\Desktop\bad_copenheimer-dev-builds\mongoBot.py", line 1157, in <module>
    bot.start()
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python312\Lib\site-packages\interactions\client\client.py", line 993, in start
    asyncio.run(self.astart(token))
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python312\Lib\site-packages\interactions\client\client.py", line 965, in astart
    await self.stop()
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python312\Lib\site-packages\interactions\client\client.py", line 1007, in stop
    await self._connection_state.stop()
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python312\Lib\site-packages\interactions\api\gateway\state.py", line 88, in stop
    self.wrapped_logger(logging.INFO, "Stopping Shard")
  File "C:\Users\Laptop\AppData\Local\Programs\Python\Python312\Lib\site-packages\interactions\api\gateway\state.py", line 142, in wrapped_logger
    self.logger.log(level, f"Shard ID {self.shard_id} | {message}", **kwargs)
TypeError: 'Logger' object is not callable
```

**Comment by Pilot1782** [comment]
Hi, this project is deprecated and has been moved [here](https://github.com/MCServerScout/Discord-Bot). If you having issues with that one, please make an issue.
